import type { Post, Project, Tool } from '@/types';

export const defaultTools: Tool[] = [
  {
    id: 1,
    name: 'Cordless Drill',
    brand: 'DeWalt',
    cat: 'Power Tools',
    model: 'DCD771',
    notes: '20V Max',
  },
  {
    id: 2,
    name: 'Circular Saw',
    brand: 'Milwaukee',
    cat: 'Power Tools',
    model: '2730-20',
    notes: '7-1/4" blade',
  },
  {
    id: 3,
    name: 'Random Orbit Sander',
    brand: 'Ryobi',
    cat: 'Finishing',
    model: 'PCE505',
    notes: '5" pad',
  },
  {
    id: 4,
    name: 'Oscillating Multi-Tool',
    brand: 'DeWalt',
    cat: 'Power Tools',
    model: 'DCS355',
    notes: 'Brushless',
  },
  {
    id: 5,
    name: 'Tape Measure',
    brand: 'Milwaukee',
    cat: 'Measuring',
    model: '48-22-7125',
    notes: '25 ft',
  },
  {
    id: 6,
    name: 'Jigsaw',
    brand: 'Makita',
    cat: 'Cutting',
    model: 'XVJ01Z',
    notes: 'Brushless',
  },
  {
    id: 7,
    name: 'Level',
    brand: 'Other',
    cat: 'Measuring',
    notes: '48 inch',
  },
  {
    id: 8,
    name: 'Brad Nailer',
    brand: 'Ryobi',
    cat: 'Fastening',
    model: 'PCN100B',
    notes: '18 gauge',
  },
];

export const defaultProjects: Project[] = [
  {
    id: 1,
    name: 'Deck Refinishing',
    type: 'DIY',
    status: 'Complete',
    cost: 320,
    time: 14,
    tools: ['Random Orbit Sander', 'Circular Saw'],
    description:
      'Stripped old stain, repaired boards, applied new semi-transparent stain.',
  },
  {
    id: 2,
    name: 'Bathroom Vanity Swap',
    type: 'DIY',
    status: 'Complete',
    cost: 650,
    time: 8,
    tools: ['Cordless Drill', 'Jigsaw', 'Level'],
    description:
      'Removed old vanity and installed a new 48" double-sink vanity.',
  },
  {
    id: 3,
    name: 'Fence Repair',
    type: 'DIY',
    status: 'In Progress',
    cost: 180,
    time: 6,
    tools: ['Cordless Drill', 'Circular Saw', 'Level'],
    description: 'Replacing 3 rotted fence posts and several damaged pickets.',
  },
  {
    id: 4,
    name: 'Kitchen Backsplash',
    type: 'DIY',
    status: 'Planned',
    cost: 220,
    time: 10,
    tools: ['Cordless Drill', 'Oscillating Multi-Tool', 'Level'],
    description: 'Install subway tile backsplash behind range and sink areas.',
  },
  {
    id: 5,
    name: 'Shed Build',
    type: 'DIY',
    status: 'Planned',
    cost: 1800,
    time: 40,
    tools: [
      'Circular Saw',
      'Cordless Drill',
      'Brad Nailer',
      'Level',
      'Tape Measure',
    ],
    description: '8x10 storage shed kit in the backyard.',
  },
];

export const defaultPosts: Post[] = [
  {
    id: 1,
    title: 'Refinishing a Deck: What Actually Works',
    date: 'Feb 12, 2025',
    tags: ['deck', 'stain', 'outdoor'],
    type: 'DIY',
    cost: '$320',
    time: '14 hrs',
    toolsUsed: 'Sander, Saw',
    materials: 'TWP 100 stain, 80/120 grit discs',
    body: `## The Project\n\nOur deck was in rough shape — peeling stain, a few soft spots, and that gray weathered look nobody wants.\n\n## Prep is Everything\n\nHonestly, the prep took longer than the actual staining. I used the **Ryobi sander** to strip the old finish, starting with 80-grit and finishing with 120-grit.\n\n> Don't skip the cleaning step. A wood brightener after sanding makes a huge difference in how the stain absorbs.\n\n## What Worked\n\n- TWP 100 series stain — goes on thin and soaks in well\n- Foam roller for field areas, brush for rails\n- Two coats with 4 hrs between\n\n## What I'd Do Differently\n\n- Rent a floor sander for the deck boards next time\n- Start earlier in the season for better drying temps`,
  },
  {
    id: 2,
    title: 'Milwaukee vs DeWalt: My Honest Take After 2 Years',
    date: 'Nov 3, 2024',
    tags: ['tools', 'review', 'comparison'],
    type: 'Review',
    toolsUsed: 'Various',
    body: `## Background\n\nI've been running both Milwaukee M18 and DeWalt 20V Max systems for about two years now.\n\n## Milwaukee Wins On\n\n- **Build quality** — feels more durable overall\n- Circular saw is excellent\n- Tape measure is best-in-class\n\n## DeWalt Wins On\n\n- **Battery runtime** — the FlexVolt stuff is impressive\n- Drill ergonomics\n- Wider ecosystem if you're just starting out\n\n## The Honest Answer\n\nBoth are great. Pick one system and **stick to it** — battery compatibility is the real value.`,
  },
];
